### ISSUE TITLE
undefined: max

### ISSUE THREAD

**Issue by matiniamirhossein** [go-jose/go-jose#111]
Hello,

I'm getting this error:

../../../go/pkg/mod/github.com/go-jose/go-jose/v4@v4.0.1/encoding.go:109:23: undefined: max

	github.com/go-jose/go-jose/v4 v4.0.1

What can be done?

**Comment by matiniamirhossein** [comment]
Seems like it will fix using go 1.21, was using 1.20.

**Comment by jsha** [comment]
Yep, that's correct! Our go.mod specifies a minimum version of 1.21 because we use `max` and underscore-separated numeric literals.
