### ISSUE TITLE
TestOpaqueKeyRoundtripJWE timeout on some arches with 4.0.1

### ISSUE THREAD

**Issue by yuzibo** [go-jose/go-jose#112]
Hi,

I uploaded 4.0.1 to Debian with 4.0.1 and found one test case failed due to timeout:

On [i386](https://ci.debian.net/packages/g/golang-github-go-jose-go-jose/testing/i386/43891631/)
```bash
719s === RUN   TestOpaqueKeyRoundtripJWE
719s panic: test timed out after 10m0s
719s running tests:
719s 	TestOpaqueKeyRoundtripJWE (7m29s)
719s 
719s goroutine 123 [running]:
719s testing.(*M).startAlarm.func1()
719s 	/usr/lib/go-1.22/src/testing/testing.go:2366 +0x38c
719s created by time.goFunc
719s 	/usr/lib/go-1.22/src/time/sleep.go:177 +0x2f
```
and if we are looking at this, we can find it failed on armel and riscv64 too. 
https://buildd.debian.org/status/package.php?p=golang-github-go-jose-go-jose&suite=sid

In fact, if it fails on armel and riscv64, it was expected :( . But I do not understand why it has timeout on i386 also.

Could you give some advice here?

**Comment by jsha** [comment]
I haven't looked at this specific case, but go-jose tests are pretty slow
since they test a big matrix of options. I'd recommend trying a longer test
timeout first.

**Comment by yuzibo** [comment]
yeah, this is my initial thoughts also, let me try on it.

**Comment by yuzibo** [comment]
>  I'd recommend trying a longer test timeout first.

Sorry, It is not easy to set `timeout` in [debian/rule](https://salsa.debian.org/go-team/packages/golang-github-go-jose-go-jose/-/blob/debian/sid/debian/rules?ref_type=heads) with Debian packaging.

Could you help me to think about a snap of pseudo-code which how to add timeout for [TestOpaqueKeyRoundtripJWE](https://github.com/go-jose/go-jose/blob/main/opaque_test.go#L289)? I tried it many times but failed.

TIA
