### ISSUE TITLE
Github actions should be upgraded so that no warnings are dumped

### ISSUE THREAD

**Issue by sarroutbi** [go-jose/go-jose#118]
An example of the Warnings being dumped here:
https://github.com/go-jose/go-jose/actions/runs/9070028369

![image](https://github.com/go-jose/go-jose/assets/959277/df3b2b8b-49d6-484b-9593-dab247919669)

This should be easily fixable by upgrading the different Github actions

**Comment by mcpherrinm** [comment]
I've added dependabot for github actions so we don't get behind in the future, and will upgrade them now
