### ISSUE TITLE
New release including fix

### ISSUE THREAD

**Issue by sergiught** [go-jose/go-jose#13]
Hello 👋🏻 , 

Would it be possible to get a new release that includes the fix within https://github.com/go-jose/go-jose/pull/10? 🙏🏻 

Thanks!

**Comment by sergiught** [comment]
Ping @csstaub 👋🏻

**Comment by mcpherrinm** [comment]
We'll make a new release shortly

**Comment by dennissetiawan** [comment]
Hello , can you give new release? I need the fix from https://github.com/go-jose/go-jose/commit/4342d9033dc4d2e6be90342a12ff17df463beac2

**Comment by rittneje** [comment]
Looks like this can be closed with the release of v3.0.2.
