### ISSUE TITLE
Build broken since go-jose/v4 "undefined: max"

### ISSUE THREAD

**Issue by timmalich** [go-jose/go-jose#145]
We are using github.com/coreos/go-oidc/v3 v3.11.0 which adds an indirect dependency to go-jose/v4.0.4

Since we upgraded from go-oidc/v3 v3.9.0 our build is broken with the following error:
```
36.26 # github.com/go-jose/go-jose/v4
36.26 /go/pkg/mod/github.com/go-jose/go-jose/v4@v4.0.4/encoding.go:109:23: undefined: max
36.26 note: module requires Go 1.21

```
We are compiling with go 1.23

Are we doing something stupid or is this really an issue since at least jose v4.0.2?

**Comment by mcpherrinm** [comment]
`max` was added to Go in 1.21.  https://tip.golang.org/ref/spec#Min_and_max

Are you sure you’re compiling with 1.23? The output suggests you are using an older version.

**Comment by mcpherrinm** [comment]
I’ll comment on the oidc issue, and we can discuss there, as it’s your direct dependency.

This package is in use in many places. It isn’t broken.
