### ISSUE TITLE
v4.0.4 not listed as latest

### ISSUE THREAD

**Issue by rittneje** [go-jose/go-jose#147]
For some reason, GitHub still says that v4.0.3 is the latest release, even though v4.0.4 was released a month ago.

![image](https://github.com/user-attachments/assets/1b7b6bc0-ba9d-4bc8-b942-a31ed3982790)

**Comment by mcpherrinm** [comment]
Thanks, fixed.

Github has a checkbox, "Set as latest", in releases.  That way you can have release candidates or betas or whatever which aren't the "latest". I checked the box on 4.0.4.
