### ISSUE TITLE
illegal base64 data at input byte 8

### ISSUE THREAD

**Issue by zetaab** [go-jose/go-jose#152]
I am running following code https://gist.github.com/zetaab/ccc2b9b55d7983cd233b63cdee62e3a3 and will get following as result:

```
% go run main.go 
error fetching JWKS: illegal base64 data at input byte 8
exit status 1
```

The issue is line https://github.com/go-jose/go-jose/blob/main/encoding.go#L167 if I modify it from `RawURLEncoding` -> `StdEncoding` it starts working.

Ideas how to get this working? Should go-jose like fallback to StdEncoding if RawURLEncoding fails?

**Comment by dims** [comment]
looks like this has come up before - https://github.com/go-jose/go-jose/issues/18#issuecomment-1385781151

**Comment by mcpherrinm** [comment]
I believe go-jose has the correct behaviour now. Changing from Base64URL as specified by the RFC to non-url-safe-base64 isn’t something I think we should do.  If you have an mis-encoded JWKS and the source won’t fix it, you could always do a find-and-replace first to fix up the encoding.
