### ISSUE TITLE
Export disclaimer - does it need to be there?

### ISSUE THREAD

**Issue by Jamstah** [go-jose/go-jose#61]
There is an export disclaimer in the readme:
> Disclaimer: This library contains encryption software that is subject to the U.S. Export Administration Regulations. You may not export, re-export, transfer or download this code or any part of it in violation of any United States law, directive or regulation. In particular this software may not be exported or re-exported in any form or on any media to Iran, North Sudan, Syria, Cuba, or North Korea, or to denied persons or entities mentioned on any US maintained blocked list.

However, the crypto in this repo all seems to use golang crypto modules rather than implement crypto itself, and the golang crypto modules are fine for export afaik: https://groups.google.com/g/golang-dev/c/RDlJVoki8R0

Does this project really need the disclaimer?

**Comment by mcpherrinm** [comment]
I've confirmed with our counsel that open-source projects should be exempt, and we should consider removing it.
