### ISSUE TITLE
v3.0.0 release notes

### ISSUE THREAD

**Issue by rittneje** [go-jose/go-jose#8]
Please fill in the [v3.0.0 release notes](https://github.com/go-jose/go-jose/releases/tag/v3.0.0) with details about what changes were introduced. In particular, it would be helpful to know what the breaking changes are, and how to properly upgrade from v2.

Also, the README still says that v3 is "unstable", which I assume is no longer true as of this release.

**Comment by rittneje** [comment]
ping @csstaub

**Comment by csstaub** [comment]
Thanks for the ping, I missed your original message. I will take some time to update this.

**Comment by rittneje** [comment]
@csstaub Were there breaking changes from v2 to v3 that developers need to account for? The release notes are pretty vague on the matter.

**Comment by mcpherrinm** [comment]
We are approaching on a v4, which does have release notes.
