### ISSUE TITLE
Misleading information on pkg.go.dev

### ISSUE THREAD

**Issue by kucherenkovova** [go-jose/go-jose#91]
In the [readme section](https://pkg.go.dev/github.com/go-jose/go-jose/v3#section-readme) you can see that v2 is recommended as the current stable version. However, it's no longer true, according to your github repo.

<img width="770" alt="image" src="https://github.com/go-jose/go-jose/assets/4640115/100be3e8-3905-4c58-9688-5fd0d3f3c093">

**Comment by mcpherrinm** [comment]
Thanks, that is indeed outdated.

**Comment by mcpherrinm** [comment]
3.0.2 has been tagged without that statement.  pkg.go.dev hasn't got it yet, but it should be there soon.

**Comment by mcpherrinm** [comment]
pkg.go.dev has picked up 3.0.2
